version: "3"

services:
  db:
    container_name: database_comttrack
    #image: sameersbn/postgresql:12-20200524
    image: library/postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_DB: $DATABASE
    env_file:
      - .env
    networks:
      - botnet
    ports:
      - "5432:5432"
    volumes:
    - ./postgresql:/var/lib/postgresql

  django:
    container_name: djangoproject_comttrack
    build:
      context: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:80 --noreload"
    ports:
      - "80:80"
    networks:
      - botnet
    restart: always
    env_file:
      - .env
    depends_on:
      - db

networks:
  botnet:
    driver: bridge